# Generated by Django 4.0.4 on 2022-06-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exampleevent",
            name="event_type",
            field=models.IntegerField(
                choices=[
                    (0, "Default"),
                    (10, "Labeling Started"),
                    (20, "Labeling Completed"),
                    (30, "Labeling Error"),
                    (40, "Labeling Updated"),
                    (50, "Labeling Deleted"),
                ],
                default=0,
            ),
        ),
    ]
