# Generated by Django 4.0.4 on 2022-06-21 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
