# Generated by Django 4.0.4 on 2022-06-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="media_type",
            field=models.IntegerField(choices=[(0, "Image")], default=0),
        ),
    ]
