# Generated by Django 4.0.4 on 2022-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='fingerprint',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='fingerprint',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
