# Generated by Django 4.0.4 on 2022-06-17 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleTag',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='properties',
            new_name='matadata',
        ),
        migrations.RemoveField(
            model_name='example',
            name='media_url',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'Image'), (1, 'Vieo'), (2, 'Audio'), (3, 'Text')], default=0)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.example')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
