# Generated by Django 4.0.4 on 2022-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_example_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
