# Generated by Django 4.0.4 on 2022-06-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_exampletag_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='matadata',
            new_name='metadata',
        ),
    ]
