# Generated by Django 4.0.4 on 2022-05-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_example_created_by_remove_loop_created_by"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Loop",
            new_name="Workflow",
        ),
    ]
