# Generated by Django 4.0.4 on 2022-06-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_example_annotation_example_prediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='annotation',
            new_name='annotations',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='prediction',
            new_name='predictions',
        ),
    ]
