# Generated by Django 4.0.4 on 2022-06-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_issue_first_seen_issue_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='fingerprint',
            field=models.TextField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='key',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
