# Generated by Django 4.0.4 on 2022-05-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_loop_workflow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="example",
            old_name="loop",
            new_name="workflow",
        ),
    ]
