# Generated by Django 4.0.4 on 2022-06-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_annotation_example_annotations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='tags',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
