# Generated by Django 4.0.4 on 2022-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_matadata_example_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Image'), (2, 'Vieo'), (3, 'Audio'), (4, 'Text')], default=0),
        ),
    ]
