# Generated by Django 4.0.4 on 2022-06-15 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_example_tags_issue_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.example')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
