# Generated by Django 4.0.4 on 2022-07-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_project_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='timestamp',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
