# Generated by Django 4.0.4 on 2022-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='key',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
