# Generated by Django 4.0.4 on 2022-06-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_example_tags_remove_issue_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='status',
        ),
    ]
