# Generated by Django 4.0.4 on 2022-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_example_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='last_seen',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
