version: "3"

services:
  db:
    image: postgres:14
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hulahoop
      - POSTGRES_USER=hulahoop
      - POSTGRES_PASSWORD=hulahoop
  app:
    build: ..
    command: ["./entrypoint-dev.sh"]
    volumes:
      - ../src:/opt/hulahoop
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=hulahoop
      - POSTGRES_USER=hulahoop
      - POSTGRES_PASSWORD=hulahoop
    depends_on:
      - db
