from .index import index
from .project_list import project_list
from .project_detail import project_detail
from .project_create import project_create
from .project_settings import project_settings
from .project_dashboard import project_dashboard
from .project_issues import project_issues
from .example_list import example_list
from .example_detail import example_detail
