version: "3"

services:
  db:
    container_name: hulahoop_db
    image: postgres:14-alpine
    volumes:
      - /opt/hulahoop/volumes/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.prod

  redis:
    container_name: hulahoop_redis
    image: redis:6-alpine
    command: redis-server
    volumes:
      - /opt/hulahoop/volumes/redis:/var/lib/redis
      - /opt/hulahoop/volumes/etc/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  app:
    container_name: hulahoop_app
    build: ""
    command: gunicorn hulahoop.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  celery_worker:
    container_name: hulahoop_celery_worker
    build: ""
    command: "./celery-worker.sh"
    volumes:
      - ./src:/opt/hulahoop
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app

  nginx:
    container_name: hulahoop_nginx
    image: nginx:1.23-alpine
    ports:
      - 1337:80
    depends_on:
      - app

