# Production environmet. For the dev environment, see docker-compose.dev.yml
version: "3"

services:
  db:
    container_name: hulahoop_db
    image: postgres:14-alpine
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    container_name: hulahoop_redis
    image: redis:6-alpine
    command: redis-server
    volumes:
      - ./volumes/redis:/var/lib/redis
      - ./etc/redis:/usr/local/etc/redis
    ports:
      - "6379:6379"

  app:
    container_name: hulahoop_app
    build: ""
    command: gunicorn hulahoop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./volumes/static:/var/www/hulahoop/static
      - ./volumes/lock:/var/lock
    expose:
      - 8000
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery_worker:
    container_name: hulahoop_celery_worker
    build: ""
    command: "./celery-worker.sh"
    volumes:
      - ./volumes/lock:/var/lock
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app

  nginx:
    container_name: hulahoop_nginx
    image: nginx:1.23-alpine
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d
      - ./volumes/static:/var/www/hulahoop/static
    ports:
      - 80:80
    depends_on:
      - app

