version: "3"

services:
  db:
    container_name: hulahoop_db
    image: postgres:14-alpine
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hulahoop
      - POSTGRES_USER=hulahoop
      - POSTGRES_PASSWORD=hulahoop

  redis:
    container_name: hulahoop_redis
    image: redis:6-alpine
    command: redis-server
    volumes:
      - ./.data/redis:/var/lib/redis
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  app:
    container_name: hulahoop_app
    build: ""
    command: "./entrypoint-dev.sh"
    volumes:
      - ./src:/opt/hulahoop
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=hulahoop.dev_settings
      - DJANGO_LOG_LEVEL=DEBUG
      - POSTGRES_NAME=hulahoop
      - POSTGRES_USER=hulahoop
      - POSTGRES_PASSWORD=hulahoop
    depends_on:
      - db
      - redis

  celery_worker:
    container_name: hulahoop_celery_worker
    build: ""
    command: "./celery-worker.sh"
    volumes:
      - ./src:/opt/hulahoop
    environment:
      - DJANGO_SETTINGS_MODULE=hulahoop.settings
      - POSTGRES_NAME=hulahoop
      - POSTGRES_USER=hulahoop
      - POSTGRES_PASSWORD=hulahoop
    depends_on:
      - db
      - redis
      - app
