# Development environmet. For the production environment, see docker-compose.yml
version: "3"

services:
  db:
    container_name: hulahoop_db
    image: postgres:14-alpine
    volumes:
      - ./dev-volumes/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

  redis:
    container_name: hulahoop_redis
    image: redis:6-alpine
    command: redis-server
    volumes:
      - ./dev-volumes/redis:/var/lib/redis
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  app:
    container_name: hulahoop_app
    build: ""
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/opt/hulahoop
      - ./dev-volumes/lock:/var/lock
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  celery_worker:
    container_name: hulahoop_celery_worker
    build: ""
    command: "./celery-worker.sh"
    volumes:
      - ./src:/opt/hulahoop
      - ./dev-volumes/lock:/var/lock
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
