# Generated by Django 4.0.4 on 2022-05-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='created_by',
        ),
    ]
